#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("data.collection.Droid.Resource", IsApplication=true)]

namespace data.collection.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::data.collection.Droid.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::data.collection.Droid.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::data.collection.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::data.collection.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int Navy = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon_add_location = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon_banner_info = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_camera = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_camera_roll = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_done = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_pin_red = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_take_photo = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ActionBarTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
